# Generated by Django 2.0.5 on 2018-06-06 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedetectionhistory',
            name='created',
            field=models.TimeField(default=datetime.datetime(2018, 6, 6, 17, 59, 43, 336389)),
        ),
    ]
